spring:
  mongodb:
    basepackage: com.fenlibao.pms.*.domain
    host: localhost
    port: 27017
  datasource:
    url: jdbc:mysql://localhost:3306/p2p
    username: root
    password: root
  mybatis:
    mapper-location: classpath*:mapper/*.xml
    config-location: classpath:mybatis-config.xml
  thymeleaf:
    cache: false

server:
    port: 9999â€‰


swagger:
    title: frame API
    description: frame applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: http://frame.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html